/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ScrollIntoView: typeof import('./src/components/ScrollIntoView.vue')['default']
    VueCommon: typeof import('./src/components/VueCommon.vue')['default']
    VueJsx: typeof import('./src/components/VueJsx.vue')['default']
  }
}
